# Site Settings
title: Bacterioplankton successions study
email: pereiramemo@gmail.com
description: >
  An opportunity to evaluate taxonomy-based vs trait-based models for predicting ecosystem processes.
baseurl: "http://pereiramemo.github.io/bacterioplankton-successions-study/"
url: "http://pereiramemo.github.io"
twitter_username: epereira
github_username:  epereira
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM